#include <iostream>
#include <fstream>
#include <string>
#include "addressbook.pb.h"
#include "myserver.h"


int main(int argc, char* argv[]) {

  // Testing myserver dep
  myserver();

  // Testing header generated by protobuf coming from myserver library
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  tutorial::AddressBook address_book;
  auto * person = address_book.add_people();
  person->set_id(1337);
  std::cout << "Test(): created a person with id 1337\n";
  // Optional:  Delete all global objects allocated by libprotobuf.
  google::protobuf::ShutdownProtobufLibrary();

  return 0;
}
